name: Setting Secrets and Variables

on:
 workflow_dispatch:

jobs:
  stagging-Environment:
    runs-on: ubuntu-24.04
    environment: stagging
    env:
      # Inject Repository secrets and variable into shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET}}
      EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}

      # Inject Enviromnent secrets and variables into shell
      EXAMPLE_ENVIRONMENT_SECRETE: ${{secrets.EXAMPLE_ENVIRONMENT_SECRETE}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_VARIABLE}}
    
    steps:
      - name: Inspect secrets and variables
        run: |
          echo "Repository secret(masked):  $EXAMPLE_REPOSITORY_SECRET"
          echo "Repository variable: $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Environment secret(masked): $EXAMPLE_ENVIRONMENT_SECRETE"
          echo "Environment variable: $EXAMPLE_ENVIRONMENT_VARIABLE"

  production-Environment:
    runs-on: ubuntu-24.04
    environment: production
    env:
      # Inject Repository secrets and variable into shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET}}
      EXAMPLE_REPOSITORY_VARIABLE: ${{vars.EXAMPLE_REPOSITORY_VARIABLE}}

      # Inject Enviromnent secrets and variables into shell
      EXAMPLE_ENVIRONMENT_SECRETE: ${{secrets.EXAMPLE_ENVIRONMENT_SECRETE}}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{vars.EXAMPLE_ENVIRONMENT_VARIABLE_PROD}}
    
    steps:
      - name: Inspect secrets and variables
        run: |
          echo "Repository secret(masked):  $EXAMPLE_REPOSITORY_SECRET"
          echo "Repository variable: $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Environment secret(masked): $EXAMPLE_ENVIRONMENT_SECRETE"
          echo "Environment variable: $EXAMPLE_ENVIRONMENT_VARIABLE"
