name: Triggering Events

on:
  push:
    branches:
      - main

  pull_request:
    branches: 
      - main
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - "dummy-files/*.md"
      - "!dummy-files/*.txt"
  
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC


  jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is triggered by push, pull_request, or schedule events."